-- MySQL Script generated by MySQL Workbench
-- Thu Feb 26 14:18:19 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Calendar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Calendar` (
  `calendarid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `description` VARCHAR(70) NULL DEFAULT NULL,
  `dateCreated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`calendarid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Room` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `roomid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `capacity` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`roomid`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Appointment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Appointment` (
  `appointmentid` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `location` VARCHAR(30) NULL DEFAULT NULL,
  `starttime` DATETIME NOT NULL,
  `endtime` DATETIME NOT NULL,
  `repeatEndDate` DATE NULL DEFAULT NULL,
  `repeat` INT(11) NULL DEFAULT NULL,
  `Calendar_calendarid` INT(11) NOT NULL,
  `Room_roomid` INT(11) NOT NULL,
  PRIMARY KEY (`appointmentid`, `Calendar_calendarid`),
  INDEX `fk_Appointment_Calendar1_idx` (`Calendar_calendarid` ASC),
  INDEX `fk_Appointment_Room1_idx` (`Room_roomid` ASC),
  CONSTRAINT `fk_Appointment_Calendar1`
    FOREIGN KEY (`Calendar_calendarid`)
    REFERENCES `mydb`.`Calendar` (`calendarid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Room1`
    FOREIGN KEY (`Room_roomid`)
    REFERENCES `mydb`.`Room` (`roomid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `email` VARCHAR(45) NOT NULL,
  `domene` VARCHAR(30) NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `passwordHash` VARCHAR(256) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(60) NOT NULL,
  `phone` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`Attendee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Attendee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Attendee` (
  `Appointment_Calendar_calendarid` INT(11) NOT NULL,
  `Appointment_appointmentid` INT(11) NOT NULL,
  `User_email` VARCHAR(30) NOT NULL,
  `timeInvited` DATETIME NULL DEFAULT NULL,
  `timeAnswered` DATETIME NULL DEFAULT NULL,
  `willAttend` TINYINT(1) NULL DEFAULT NULL,
  `isOwner` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Appointment_Calendar_calendarid`, `Appointment_appointmentid`, `User_email`),
  INDEX `fk_User_has_Appointment_Appointment1_idx` (`Appointment_appointmentid` ASC, `Appointment_Calendar_calendarid` ASC),
  INDEX `fk_Attendee_User1_idx` (`User_email` ASC),
  CONSTRAINT `fk_User_has_Appointment_Appointment1`
    FOREIGN KEY (`Appointment_appointmentid` , `Appointment_Calendar_calendarid`)
    REFERENCES `mydb`.`Appointment` (`appointmentid` , `Calendar_calendarid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attendee_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `mydb`.`User` (`domene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`GroupCalendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GroupCalendar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GroupCalendar` (
  `Calendar_calendarid` INT(11) NOT NULL,
  `User_email` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Calendar_calendarid`, `User_email`),
  INDEX `fk_User_has_Calendar1_Calendar1_idx` (`Calendar_calendarid` ASC),
  INDEX `fk_GroupCalendar_User1_idx` (`User_email` ASC),
  CONSTRAINT `fk_User_has_Calendar1_Calendar1`
    FOREIGN KEY (`Calendar_calendarid`)
    REFERENCES `mydb`.`Calendar` (`calendarid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GroupCalendar_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `mydb`.`User` (`domene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Notification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Notification` (
  `Appointment_appointmentid` INT(11) NOT NULL,
  `Appointment_Calendar_calendarid` INT(11) NOT NULL,
  `User_email` VARCHAR(30) NOT NULL,
  `text` VARCHAR(200) NULL DEFAULT NULL,
  `seen` TINYINT(1) NULL DEFAULT NULL,
  `sent` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Appointment_appointmentid`, `Appointment_Calendar_calendarid`, `User_email`),
  INDEX `fk_User_has_Appointment_Appointment2_idx` (`Appointment_appointmentid` ASC, `Appointment_Calendar_calendarid` ASC),
  INDEX `fk_Notification_User1_idx` (`User_email` ASC),
  CONSTRAINT `fk_User_has_Appointment_Appointment2`
    FOREIGN KEY (`Appointment_appointmentid` , `Appointment_Calendar_calendarid`)
    REFERENCES `mydb`.`Appointment` (`appointmentid` , `Calendar_calendarid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notification_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `mydb`.`User` (`domene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`Utility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Utility` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Utility` (
  `utilityid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`utilityid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`Room_has_Utility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Room_has_Utility` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Room_has_Utility` (
  `Room_roomid` INT(11) NOT NULL,
  `Utility_utilityid` INT(11) NOT NULL,
  PRIMARY KEY (`Room_roomid`, `Utility_utilityid`),
  INDEX `fk_Room_has_Utility_Utility1_idx` (`Utility_utilityid` ASC),
  INDEX `fk_Room_has_Utility_Room_idx` (`Room_roomid` ASC),
  CONSTRAINT `fk_Room_has_Utility_Room`
    FOREIGN KEY (`Room_roomid`)
    REFERENCES `mydb`.`Room` (`roomid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Room_has_Utility_Utility1`
    FOREIGN KEY (`Utility_utilityid`)
    REFERENCES `mydb`.`Utility` (`utilityid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User_has_Calendar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Calendar` (
  `Calendar_calendarid` INT(11) NOT NULL,
  `User_email` VARCHAR(30) NOT NULL,
  `color` VARCHAR(7) NULL DEFAULT NULL,
  `isVisible` TINYINT(1) NULL DEFAULT NULL,
  `isOwner` TINYINT(1) NULL DEFAULT NULL,
  `notifications` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Calendar_calendarid`, `User_email`),
  INDEX `fk_User_has_Calendar_Calendar1_idx` (`Calendar_calendarid` ASC),
  INDEX `fk_User_has_Calendar_User1_idx` (`User_email` ASC),
  CONSTRAINT `fk_User_has_Calendar_Calendar1`
    FOREIGN KEY (`Calendar_calendarid`)
    REFERENCES `mydb`.`Calendar` (`calendarid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Calendar_User1`
    FOREIGN KEY (`User_email`)
    REFERENCES `mydb`.`User` (`domene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
